resources:
  - url: http://127.0.0.1:5000/pallone-card.js
    type: module
views:
  - cards:
      - type: custom:pallone-card
        name: Pallone card
        entity: sensor.pallone
        test_gui: true
